version: '3'

services:
  php:
    build: docker/php
    expose:
      - "9000"
    volumes:
      - ./symfony:/usr/share/nginx/html/symfony:cached
      - ./logs:/var/log
    networks:
      - symfony-base
  web:
    build: docker/nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ./symfony:/usr/share/nginx/html/symfony:cached
      - ./logs:/var/log/nginx
    networks:
      - symfony-base

networks:
  symfony-base:
    driver: bridge
